SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[AppUser_History](
	[AppUser_History_PK] [decimal](18, 0) IDENTITY(1,1) NOT NULL,
	[AppUser_FK] [decimal](18, 0) NOT NULL,
	[UserPassword] [char](40) NOT NULL,
	[DateAdded] [datetime] NOT NULL,
 CONSTRAINT [PK_AppUser_History] PRIMARY KEY NONCLUSTERED 
(
	[AppUser_History_PK] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
