SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Process_Date](
	[ProcessDate_PK] [decimal](18, 0) IDENTITY(1,1) NOT NULL,
	[ProcessDate] [datetime] NOT NULL,
	[ProcessStatus_FK] [decimal](18, 0) NOT NULL,
	[IsUndo] [bit] NOT NULL,
	[ModifiedDateTime] [datetime] NOT NULL,
	[User_FK] [decimal](18, 0) NOT NULL,
	[Details] [varchar](500) NOT NULL,
 CONSTRAINT [PK_Process_Date] PRIMARY KEY NONCLUSTERED 
(
	[ProcessDate_PK] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE UNIQUE CLUSTERED INDEX [IX_Process_Date] ON [dbo].[Process_Date]
(
	[ProcessDate] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
