SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Trading_Settings](
	[OrderCutoffHour] [int] NOT NULL,
	[OrderCutoffMinute] [int] NOT NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
