@echo off

SETLOCAL

SET DEST_DIR=%DATABASE_BACKUP_DIR%\archive
IF NOT EXIST %DEST_DIR% (MKDIR %DEST_DIR%)
echo.

SET ARCHIVE_DIR=\\%DMS_SQLSERVER1_PRD_A_PRI%\tbs_autorecon_bcp\archive
SET TIMESTAMP=%1
SET DATABASE_NAME=%2

SET FILES="%TIMESTAMP%_%DATABASE_NAME%.7z"
robocopy "%ARCHIVE_DIR%" "%DEST_DIR%" /R:5 /Z /NDL /IF %FILES%
EXIT /b 0