@echo off

SETLOCAL

SET TIMESTAMP=%1
SET DATABASE_NAME=%2

cd %DATABASE_BACKUP_DIR%

IF EXIST %DATABASE_NAME% (DEL /Q %DATABASE_NAME%)
IF NOT EXIST %DATABASE_NAME% (MKDIR %DATABASE_NAME%)

set FILENAME=archive\%TIMESTAMP%_%DATABASE_NAME%.7z
"%ZIP_EXE_DIR%"\7z.exe x -y %FILENAME% %DATABASE_NAME%\

if ERRORLEVEL 1 (EXIT /b 1)
